doc/development.md, server/camphoric_server/settings.py, server/requirements.txt
Partially addresses #7 by adding the necessary changes to the documentation, settings.py and requirements.txt
=> Setup postgreSQL.

doc/development.md, server/camphoric_server/settings.py, server/requirements.txt
=> Use .env file for secrets, etc.

doc/development.md, server/requirements.txt, server/tests/test_models.py
Changed requirements.txt and development.md to reflect importing unittests.
Setup a basic test suite that can be expanded.
=> Create basic test suite.

client/src/components/AdminPage/AdminPage.css, client/src/components/AdminPage/AdminPage.tsx, client/src/components/AdminPage/index.ts, client/src/components/App/App.tsx
I have confirmed that codesplitting works as we hoped!
Closes #59 
Closes #35
=> Add codesplitting and admin interface holding place

client/src/components/AdminPage/AdminLoginCheck.tsx, client/src/components/AdminPage/AdminPage.css, client/src/components/AdminPage/AdminPage.tsx, client/src/components/AdminPage/index.ts, client/src/components/Login/Login.tsx, client/src/components/Login/index.ts, client/src/components/Spinner/Spinner.tsx
=> Create admin page with basic login

client/src/components/AdminPage/AdminPage.tsx, client/src/components/AdminPage/GuardedRoute.tsx, client/src/components/AdminPage/components/EventAdmin/EventAdmin.scss, client/src/components/AdminPage/components/EventAdmin/EventAdmin.tsx, client/src/components/AdminPage/components/EventAdmin/components/Home.tsx, client/src/components/AdminPage/components/EventAdmin/components/Lodging.tsx, client/src/components/AdminPage/components/EventAdmin/components/NavBar.tsx, client/src/components/AdminPage/components/EventAdmin/components/Registrations.tsx, client/src/components/AdminPage/components/EventAdmin/components/Reports.tsx, client/src/components/AdminPage/components/EventAdmin/components/Settings.tsx, client/src/components/AdminPage/components/EventChooser.tsx, client/src/components/AdminPage/components/OrganizationChooser.tsx, client/src/components/AdminPage/hooks.ts, client/src/components/App/App.tsx, client/src/components/App/Splash.tsx, client/src/components/NaturalNumberInput/index.tsx, client/src/components/RegisterPage/RegisterPage.scss, client/src/components/RegisterPage/RegisterPage.tsx, client/src/global.d.ts, client/src/index.scss
This is an addon MR to the other MR that cleans up and adds to the basic premise
=> Will add event editing

client/src/components/AdminPage/components/EventAdmin/components/Home.tsx, client/src/components/AdminPage/components/EventAdmin/components/Lodging.tsx, client/src/components/AdminPage/components/EventAdmin/components/Registrations.tsx, client/src/components/AdminPage/components/EventAdmin/components/Reports.tsx, client/src/components/AdminPage/components/EventAdmin/components/Settings.tsx, client/src/components/AdminPage/components/Login/Login.tsx, client/src/components/AdminPage/hooks.ts, client/src/components/App/App.tsx
Fixes:
- The guarded route was not re-rendering after login
- The login page was not properly styled
- There were warnings about unused variables
=> Cleanup login re-render

client/src/components/AdminPage/AdminPage.tsx, client/src/components/AdminPage/GuardedRoute.tsx, client/src/components/AdminPage/components/EventAdmin/EventAdmin.scss, client/src/components/AdminPage/components/EventAdmin/EventAdmin.tsx, client/src/components/AdminPage/components/EventAdmin/components/Home.tsx, client/src/components/AdminPage/components/EventAdmin/components/Lodging.tsx, client/src/components/AdminPage/components/EventAdmin/components/NavBar.tsx, client/src/components/AdminPage/components/EventAdmin/components/RegistrationSearchResult.tsx, client/src/components/AdminPage/components/EventAdmin/components/Registrations.tsx, client/src/components/AdminPage/components/EventAdmin/components/Reports.tsx, client/src/components/AdminPage/components/EventAdmin/components/Settings.tsx, client/src/components/AdminPage/components/EventAdmin/components/ShowRawJSON.tsx, client/src/components/AdminPage/components/EventAdmin/components/createEventEditForm.ts, client/src/components/AdminPage/components/OrganizationChooser.tsx, client/src/components/AdminPage/hooks.ts, client/src/components/App/App.tsx, client/src/components/App/Splash.tsx, client/src/global.d.ts
This update will allow you to search registrations on the UI
=> Will add basic search

client/src/components/AdminPage/components/EventAdmin/EventAdmin.tsx, client/src/components/AdminPage/components/EventAdmin/components/RegistrationEdit.tsx, client/src/components/AdminPage/components/EventAdmin/components/RegistrationSearchResult.tsx, client/src/components/AdminPage/components/EventAdmin/components/Registrations.tsx, client/src/components/AdminPage/hooks.ts, client/src/global.d.ts
TODO: next step is to refactor the form logic so that it's a separate component.
=> Preliminary edit reg and camper

client/Dockerfile, client/package.json, client/yarn.lock, data/lark/loadData.mjs, development-setup-wizard.mjs, doc/development.md, docker-compose.yml, package.json, remove-all-docker-artifacts, server/Dockerfile, yarn.lock
This creates a script that makes it really easy to start development.  This is really the culmination of all the discussion we've been having in issue #126 ,  plus a some minor tweaks and fixes.
=> Add development setup wizard

development-setup-wizard.mjs, doc/development.md, docker-compose.yml
Fix errors associated with older versions of macOS and docker.
=> Fix setup wizard

doc/manual-development.md, server/Pipfile, server/Pipfile.lock, server/camphoric/models.py, server/tests/test_models.py, windows notes
Also update path for .env file in manual development documentation
Update dependencies in pipfile to include psycopg2-binary for Windows installation
=> Add test for lodging notes default to blank

client/src/global.d.ts, client/src/hooks/Provider.tsx, client/src/hooks/admin.ts, client/src/navigation/EventAdminContainer/index.tsx, client/src/navigation/RouterConfig.tsx, client/src/pages/EventAdminCampers/CamperEdit.tsx, client/src/pages/EventAdminCampers/CamperSearchResult.tsx, client/src/pages/EventAdminCampers/EventAdminCampers.tsx, client/src/pages/EventAdminCampers/index.ts, client/src/pages/EventAdminCampers/styles.scss, client/src/pages/EventAdminRegistrations/RegistrationSearchResult.tsx, client/src/utils/objectKeys.js
Adds camper search and a basic non-functional camper edit form
=> Add camper search UI

data/lark/loadData.mjs, package.json, server/camphoric/models.py, server/camphoric/views.py, server/tests/test_views.py
This PR adds a sample report, and it's pretty easy to add more.  It also does these quick and dirty things:
- Add quick script running via `yarn run`
- Add better debugging for data import
=> Add sample reports

.editorconfig, .gitignore, client/src/navigation/EventAdminContainer/NavBar.tsx, client/src/navigation/EventAdminContainer/index.tsx, client/src/navigation/EventAdminContainer/styles.scss, client/src/navigation/RouterConfig.tsx, client/src/pages/EventAdminCampers/EventAdminCampers.tsx, client/src/pages/EventAdminCampers/styles.scss, client/src/pages/EventAdminRegistrations/EventAdminRegistrations.tsx, client/src/pages/Register/index.tsx, client/src/utils/fuse.ts, data/lark/camperSchema.mjs, data/lark/lodgings.mjs, data/lark/registrationSchema.mjs, data/lark/registrationUISchema.mjs, server/camphoric_server/settings.py
* Make it so camper/reg shows first 10 when not searching
* Remove unnecessary lazy loading
* Provide better styling for admin nav-bar
* Add ts and tsx files to editorconfig
* Reference strange static settings
=> Will update more stuff

.env.example/local/django.env, .env.example/local/shared.env, .github/workflows/django.yml, client/src/pages/EventAdminReports/EventAdminReports.tsx, client/src/pages/EventAdminReports/ReportView.tsx, data/lark/loadData.mjs, data/lark/lodgings.mjs, development-setup-wizard.mjs, docker-compose.yml, reset-db
* Add shared.env
* Adjust lodging numbers for lark 
* Refactor AdminReports to use components/Modal
=> Add better automated createsuperuser for dev deployments 

data/lark/camperMeals.mjs, data/lark/camperSchema.mjs, data/lark/confirmationEmailTemplate.mjs, data/lark/loadData.mjs, data/lark/lodgings.mjs, data/lark/pricing/camperPricingLogic.mjs, data/lark/registrationSchema.mjs, data/lark/testRegistrations.mjs, server/camphoric/views.py
* Add markdown table to confirmation email (TODO: markdown to html for python emails)
* Add camper pricing to template vals for reg emails
* Add logic for avoiding sending email for tests
* Get rid of enumNames for better reports
* Add any cabin/tent options
* Clean up spaces on ends of lines
=> Will more misc changes

data/lark/confirmationEmailTemplate.mjs, data/lark/loadData.mjs, server/Dockerfile, server/Pipfile, server/Pipfile.lock, server/camphoric/views.py, server/tests/test_views.py
* Add subject to confirmation email template
* Add md->html email for registration and invitations
* Remove test regs from post to event
Resulting email:
=> Add markdown email rendering

data/lark/loadData.mjs, server/tests/test_views.py
Also rename some vars for clarity in lark/loadData
=> Test html conversion of reg invitation

data/lark_campout/camperSchema.mjs, data/lark_campout/confirmationEmailTemplate.mjs, data/lark_campout/confirmationPageTemplate.mjs, data/lark_campout/loadData.mjs, data/lark_campout/lodgings.mjs, data/lark_campout/pricing/camperPricingLogic.mjs, data/lark_campout/pricing/pricing.mjs, data/lark_campout/pricing/registrationPricingLogic.mjs, data/lark_campout/registrationSchema.mjs, data/lark_campout/registrationTypes.mjs, data/lark_campout/registrationUISchema.mjs, data/lark_campout/testRegistrations.mjs, data/loadAllData.mjs, docker-compose.yml, package.json, reset-db
- Add campout data
- Add lark campout event
=> Add campout and import script

data/getAuthInfo.mjs, data/loadAllData.mjs, development-setup-wizard.mjs
- Remove unused auth function
- Make setup wizard use new loading script
=> Cleanup data import auth

.env.example/local/shared.env, data/lark/loadData.mjs, data/lark_campout/loadData.mjs, data/loadAllData.mjs, data/loadOrganizations.mjs
This adds two new environment variables to the env file:
- CAMPHORIC_TEST_GMAIL_USERNAME
- CAMPHORIC_TEST_GMAIL_PASSWORD
This should be connected to an email account which uses an app specific password: https://support.google.com/mail/answer/185833
fixes #212
The system successfully sent a confirmation email from a test gmail account after registration:
=> Implement email data for test events

server/camphoric/urls.py, server/camphoric/views.py, server/tests/test_views.py
To support lodging assignment admin interface.
Closes #219
=> Create admin endpoint for lodging schema

data/lark_campout/pricing/camperPricingLogic.mjs
Fixes the problem with the pricing logic in campout
=> Fix campout pricing

server/camphoric/serializers.py
=> Make EmailAccount.password write-only

client/src/pages/Register/RegisterStep.tsx, client/src/pages/Register/component.tsx, client/src/pages/Register/index.tsx
=> Fix focus on error for phone number fields

client/src/pages/Register/index.tsx, data/lark_campout/pricing/camperPricingLogic.mjs, data/loadOrganizations.mjs, server/camphoric/pricing.py
fixes #259
- Make pricing logic better
- Hack server pricing for Lark Campout 2022
=> Fix pricing hack for lark campout

data/lark_campout/confirmationEmailTemplate.mjs, server/camphoric/views.py
related to #262 
This is really a hack to get around that we don't have report serializers
Fixes #260
=> Add camper lodging to email template

client/package-lock.json, client/package.json, client/src/components/Template/util.ts
=> Make links in templates open in new tab/window

client/src/components/JsonSchemaForm/__tests__/calculatePrice.test.ts, client/src/pages/Register/PayPalButtons.tsx, client/src/pages/Register/PaymentStep.tsx, client/src/pages/Register/index.tsx, client/src/pages/Register/styles.scss
=> Add overlay when processing captured payment

client/src/pages/Register/RegisterStep.tsx, client/src/pages/Register/component.tsx, client/src/pages/Register/index.tsx
=> Set camper[0]'s email to main email value on blur

data/lark_campout/camperSchema.mjs, data/lark_campout/confirmationEmailTemplate.mjs
=> Make confirmation email more mobile friendly

client/src/pages/Register/index.tsx
=> Add saving unfinished forms to local storage

client/src/pages/Register/RegisterStep.tsx, client/src/pages/Register/component.tsx, client/src/pages/Register/index.tsx
Reverts camphoric/camphoric#269
Reopens #253
We got reports in the field that this was failing
=> Revert "Set camper[0]'s email to main email value on blur"

.env.example/local/django.env, .gitignore, server/Dockerfile, server/Pipfile, server/Pipfile.lock, server/backup/README.md, server/camphoric_server/settings.py
I tested this with an AWS s3 storage bucket and it works great.
=> Install and configure basic backup

client/src/components/Modal/ConfirmDialog.tsx, client/src/components/Modal/Modal.tsx, client/src/global.d.ts, client/src/hooks/api.ts, client/src/pages/EventAdmin/Lodging.tsx, client/src/pages/EventAdmin/LodgingNodeDisplay.tsx, client/src/pages/EventAdminCampers/CamperEdit.tsx, client/src/pages/EventAdminRegistrations/EditTab/PaymentTab.tsx, client/src/pages/EventAdminRegistrations/EditTab/RegistrationEdit.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/ControlColumn.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/InviteModal.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/RegTypeModal.tsx, client/src/pages/EventAdminReports/EventAdminReports.tsx, client/src/pages/EventAdminReports/ReportView.tsx, client/src/utils/display.ts, data/lark_campout/loadData.mjs, data/lark_campout/reports.mjs, data/lark_campout/testRegistrations.mjs
- Add ability to delete registrations
- Add ability to delete campers
- Change 'handle' to 'on' for modal prop callback
- Add some better default lodging display
- Add lodging lookup so that it can be added to the reports
=> Various Admin UI Improvements

client/package-lock.json, client/package.json, client/src/components/Input/TextArea.tsx, client/src/components/TemplateHelp/TemplateHelp.tsx, client/src/components/TemplateHelp/index.ts, client/src/pages/EventAdmin/LodgingNodeDisplay.tsx, client/src/pages/EventAdminReports/EventAdminReports.tsx, client/src/pages/EventAdminReports/ReportEditForm.tsx, client/src/pages/EventAdminReports/ReportTab.tsx, client/src/pages/EventAdminReports/ReportView.tsx
- Make saving report auto switch to view report
- Add template help modal
- Fix lodging typing
- Improve prelim lodging display
=> More misc UI/UX admin improvements

client/src/global.d.ts, client/src/pages/EventAdminLodging/CamperPopOver.tsx, client/src/pages/EventAdminLodging/EventAdminLodging.tsx, client/src/pages/EventAdminLodging/styles.scss, server/camphoric/lodging.py, server/tests/test_get_lodging_schema.py, server/tests/test_views.py
- Add lodging notes to the form sent to the register form
- Add lodging notes to the admin interface
- Fix tests that involve lodging notes and lodging in general (involves some light refactoring)
=> Finish adding lodging notes to camper

client/src/components/ObjectAsList.tsx, client/src/components/Table.tsx
Allows sub-objects in a table display to be rendered as a multi-tier list
=> Improve display of array/hash in Table

client/src/components/Template/handlebarsHelpers.ts, client/src/components/Template/util.ts, client/src/components/TemplateHelp/HelperDocs.tsx, client/src/components/TemplateHelp/TemplateHelp.tsx, client/src/components/TemplateHelp/helpText.ts, client/src/components/TemplateHelp/styles.scss, client/src/pages/EventAdminReports/EventAdminReports.tsx
=> Add help text for handlebars helpers

server/camphoric/lodging.py, server/tests/test_lodging_tree.py
Allow overbooking without affecting remaining capacity.
closes #237
=> Keep remaining lodging capacity non-negative

server/Pipfile, server/Pipfile.lock
Tests pass, but this hasn't been manually tested yet.
closes #224
=> Upgrade Django to 4.x

server/Pipfile, server/Pipfile.lock, server/camphoric/views.py, server/camphoric_server/settings.py
Allows listing registrations for a given event, campers for a given registration, etc.
Docs:
- https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
- https://django-filter.readthedocs.io/en/latest/index.html
=> Enable filtering via query params

client/package-lock.json, client/package.json, client/src/components/JsonSchemaForm/fields/Address/AddressField.tsx, client/src/components/JsonSchemaForm/fields/Address/AddressFieldErrors.tsx, client/src/components/JsonSchemaForm/fields/Campers.tsx, client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingRequested.tsx, client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingRequestedErrors.tsx, client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingSelect.tsx, client/src/components/JsonSchemaForm/styles.scss, client/src/pages/Register/RegisterStep.tsx, client/src/pages/Register/styles.scss, client/src/pages/Register/transformErrors.ts, client/src/utils/display.ts
- Add better labeling for campers in reg form
- Add better error messages
=> Add better button and error labels

client/src/components/JsonSchemaForm/index.tsx, server/camphoric/pricing.py, server/tests/test_pricing.py
Minor fixes for issues found while updating Family Week data.
To deploy the frontend JS fixes, I think the js-build-main branch needs to be updated with these changes.
=> Fixes for familyweek

client/src/components/JsonSchemaForm/fields/Description.tsx, client/src/components/JsonSchemaForm/styles.scss, client/src/components/JsonSchemaForm/templates/Array.tsx, data/lark/confirmationEmailTemplate.js, data/lark/regTemplateVars.js, data/lark/registrationUISchema.js
- Remove console.log
- Fix missing name in email template
- Fix dates in template vars
- Add add/remove button text ui option for arrays
- Improve styling for array items
=> More misc fixes

client/src/components/Modal/Modal.tsx, client/src/components/Spinner/FullScreen.tsx, client/src/components/Spinner/Spinner.css, client/src/components/Spinner/Spinner.tsx, client/src/components/Spinner/index.ts, client/src/pages/EventAdminRegistrations/SpecialRegTab/InviteForm.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/RegTypeForm.tsx, client/src/pages/Register/transformErrors.ts, data/lark/registrationTypes.js
- Add loading status for modals
- Add back subpar error messages (better than nothing)
=> More fixes

client/src/components/Template/Template.tsx, client/src/components/Template/handlebarsHelpers.ts, client/src/global.d.ts, client/src/pages/Register/RegisterStep.tsx, client/src/pages/Register/component.tsx, client/src/pages/Register/index.tsx, data/lark/camperMeals.js, data/lark/confirmationEmailTemplate.js, data/lark/confirmationPageTemplate.js, data/lark/registrationSchema.js, server/camphoric/views.py, server/tests/test_views.py
- Add large covid 19 vax required in reg form
- Remove price ticker from payment step
- Fix meal type logic
- Add deposit info to template logic
=> Fix more things before reg opening

client/src/components/Template/Template.tsx, client/src/pages/Register/PaymentStep.tsx, client/src/pages/Register/index.tsx, data/lark/camperSchema.js, data/lark/confirmationEmailTemplate.js, data/lark/registrationTypes.js
- Change reg form per Meghan's suggestions
- Fix paypal payments
=> More pre-open fixes

client/src/pages/EventAdminLodging/EventAdminLodging.tsx
=> Nullify lodging on admin unassign

client/src/components/JsonSchemaForm/index.tsx, client/src/components/JsonSchemaForm/widgets/Textarea.tsx
=> Automatically truncate textarea on maxLength

client/src/components/JsonSchemaForm/AdminEdit.tsx, client/src/components/JsonSchemaForm/JsonSchemaForm.tsx, client/src/components/JsonSchemaForm/fields/Description.tsx, client/src/components/JsonSchemaForm/index.ts, client/src/components/JsonSchemaForm/styles.scss, client/src/components/Modal/Modal.tsx, client/src/pages/EventAdminCampers/CamperEdit.tsx, client/src/pages/EventAdminCampers/CamperSearchResult.tsx, client/src/pages/EventAdminLodging/Assignment/AssignmentTab.tsx, client/src/pages/EventAdminRegistrations/EditTab/RegistrationEdit.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/InviteForm.tsx, client/src/pages/EventAdminRegistrations/SpecialRegTab/RegTypeForm.tsx, client/src/store/api.ts
- Remove some debug noise
- Move JsonSchemaForm out of index
- Make updates to camper/registration refetch both
- Make camper and reg editable in admin interface
=> Make camper and reg editable in admin interface

client/src/pages/EventAdminRegistrations/EditTab/RegistrationEdit.tsx
=> Add ability to edit registration email

client/src/navigation/GuardedRoute.tsx, client/src/navigation/Login/index.tsx, client/src/navigation/RouterConfig.tsx, client/src/store/admin/api.ts
This refactors the Login and GuardedRoute components to use the redux api toolkit
=> Fix admin login

client/src/components/JsonSchemaForm/widgets/Textarea.tsx, data/lark/camperSchema.js, data/lark/registrationSchema.js, server/Pipfile, server/Pipfile.lock, server/camphoric/views.py, server/tests/test_views.py
- Fix missing apostrophe in camper's - Fixes #363
- Add better email validation - Fixes #362
- Add help text to lodging notes on reg form - Fixes #361
=> Fix for a few small bugs

client/src/components/Template/handlebarsHelpers.ts, client/src/pages/EventAdminCampers/CamperEdit.tsx, client/src/pages/EventAdminCampers/EventAdminCampers.tsx, client/src/pages/EventAdminRegistrations/EditTab/RegistrationEdit.tsx, data/CamphoricEventCreator.js, data/lark/index.js, data/lark/testRegistrations.js, data/package-lock.json, data/package.json
- Fix test data import for lark
- Fix bug with camper not changing on click
- Fix string sorting in reports
Fixes https://github.com/camphoric/camphoric/issues/370
=> Fix camper search bug

client/src/global.d.ts, client/src/hooks/api.ts
Sample report:
```
| Last Name | First Name | Age | Camp | Lodging |
| --------- | ---------- | --- | ------- | ----- |
{{#eachLookupSort campers 'lodging' 'lodgingLookup' 'fullPath'}} | {{this.attributes.last_name}} | {{this.attributes.first_name}} | {{this.attributes.age}} | {{getLodgingValue lodging 'pathParts.0'}}  | {{getLodgingValue lodging 'fullPath'}} |
{{/eachLookupSort}}
```
Result:
=> Add path to augmented lodging

client/src/components/Template/handlebarsHelpers.ts
Example:
```
{{#each (filter campers 'attributes.age' '===' '50-64 years old')}}
- {{attributes.first_name}}
{{/each}}
{{#each (filter campers 'attributes.age' '===' '12-17 years old')}}
- {{attributes.first_name}}
{{/each}}
grand total: {{sum
(count (filter campers 'attributes.age' '===' '50-64 years old'))
(count (filter campers 'attributes.age' '===' '12-17 years old'))
}}
```
Result:
Also, just note that filters can be chained:
```
{{#each
(filter
(filter campers 'registration' '==' 6)
'attributes.last_name' '===' 'Summers'
)
}}
- {{attributes.first_name}}
{{/each}}
```
results:
=> Add filter and count helpers

client/src/components/Input/Select.tsx, client/src/global.d.ts, client/src/hooks/api.ts, client/src/pages/EventAdminLodging/EventAdminLodging.tsx, client/src/pages/EventAdminLodging/TreeView/LodgingEditForm.tsx, client/src/pages/EventAdminLodging/TreeView/LodgingNodeDisplay.tsx, client/src/pages/EventAdminLodging/TreeView/TreeView.tsx, client/src/pages/EventAdminLodging/TreeView/index.ts, client/src/pages/EventAdminLodging/TreeView/styles.scss, client/src/pages/EventAdminLodging/utils.ts, client/src/pages/EventAdminReports/EventAdminReports.tsx, client/src/pages/EventAdminReports/ReportEditForm.tsx, data/CamphoricEventCreator.js, docker-compose.yml, postgres-initdb.sql
=> Add ability to edit lodging

client/src/pages/EventAdminLodging/TreeView/LodgingEditForm.tsx, client/src/pages/EventAdminLodging/TreeView/LodgingNodeDisplay.tsx, client/src/pages/EventAdminLodging/TreeView/TreeView.tsx, client/src/pages/EventAdminLodging/TreeView/styles.scss
=> Add ability to add new lodging

Dockerfile, client/index.html, client/package.json, client/vite.config.js, logs/README.md, package.json, run-docker, server/camphoric_server/settings_default.py
- Clean up index.html
- Change assets build path to static per server configs
- Add missing server configuration
- Add standalone Dockerfile
=> Add better build settings

client/index.html, data/familyweek/reports.js, data/lark/reports.js, data/lark_campout/reports.js
- Add output type to sample data reports
- Fix favicon links
=> Misc fixes

client/src/pages/EventAdminReports/EventAdminReports.tsx, client/src/pages/EventAdminReports/RenderedReport/CSVTable.tsx, client/src/pages/EventAdminReports/ReportEditForm.tsx, client/src/pages/EventAdminReports/ReportTab.tsx, client/src/pages/Register/transformErrors.ts, server/camphoric/models.py, server/camphoric/views.py
- Remove console.log
- Change default template type to CSV
- Add a couple easy jinja ext
- Fix report edit form modal
- Fix report rendering key issues
- Remove useless print tab
=> More template fixes

client/src/pages/EventAdminCampers/CamperEdit/AdminAttributesTab.tsx, client/src/pages/EventAdminCampers/CamperEdit/CamperEdit.tsx, client/src/pages/EventAdminCampers/CamperEdit/LodgingTab.tsx, client/src/pages/EventAdminReports/RenderedReport/CSVTemplate.tsx, server/camphoric/views.py
- Improve report display and errors
- Add see/edit lodging days from camper lookup
=> Add see/edit lodging from camper edit

client/package-lock.json, client/package.json, client/src/components/CodeEditor.tsx, client/src/pages/EventAdminReports/RenderedReport/CSVTable.tsx, client/src/pages/EventAdminReports/RenderedReport/CSVTemplate.tsx, client/src/pages/EventAdminReports/RenderedReport/RenderedReport.tsx, client/src/pages/EventAdminReports/ReportEditForm.tsx, client/src/pages/EventAdminSettings/EditJSONType.tsx
- Add monico code editor for templates
- Make CodeEditor a separate component
- Use CodeEditor for editing raw JSON
=> Add monico editor for templates

client/src/pages/Register/PriceTicker.tsx, client/src/pages/Register/RegistrationStep.tsx, client/src/pages/Register/utils.ts, data/harmony/confirmationEmailTemplate.js, data/harmony/confirmationPageTemplate.js, data/harmony/dates.js, data/harmony/index.js, data/harmony/pricing/camperPricingLogic.js
I was overzealous in my fix of the price ticker, adding a spinner, it
created more problems that it solved.  This was partially because I
tried to overload the saving to local storage, and now have separated
out the problems there.
=> Fix price ticker bug

client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingRequested.tsx, data/harmony/camperSchema.js, data/harmony/confirmationEmailTemplate.js, data/harmony/confirmationPageTemplate.js, data/harmony/lodgings.js, data/harmony/pricing/camperPricingLogic.js, data/harmony/pricing/pricing.js, data/harmony/registrationSchema.js, data/harmony/registrationUISchema.js, data/harmony/testRegistrations.js
- Add created_at time to pricing logic
- Fix campership calculation (#421)
- Add link to lodging prices (#420)
- Edit campership language (#418)
- Replace covid/cancel policies with link (#417)
- Adjust meal options (#416)
- Fix confirmation page text (#414)
- Add rv sizes to harmony (#413)
=> More Harmony Fixes

doc/development.md, docker-compose.yml, server/tests/test_mail.py
Fixes for issues I had getting my dev env running
=> Gildea dev setup fixes

data/lark/confirmationEmailTemplate.js, data/lark/pricing/pricing.js, data/lark/regTemplateVars.js, data/lark/registrationSchema.js, data/package-lock.json, data/package.json
- Fix dates in templates
- Fix pricing
- Fix lark covid policy
=> will fix camps

.github/workflows/django.yml, client/src/pages/EventAdminRegistrations/SpecialRegTab/InvitationReport.tsx, data/lark/camperSchema.js, data/lark/testRegistrations.js
- **Change 'Other' to 'Non-binary' for gender**
- **Add deletions for special registrations**
=> Add deletions for special registrations

client/package-lock.json, client/package.json, client/src/components/JsonEditor/JsonEditor.tsx, client/src/components/JsonEditor/index.ts, client/src/components/TemplateHelp/TemplateHelp.tsx, client/src/pages/EventAdminLodging/EventAdminLodging.tsx, client/src/pages/EventAdminLodging/styles.scss, client/src/pages/EventAdminSettings/EditJSONType.tsx, client/src/pages/EventAdminSettings/EditSchemaTab.tsx, data/lark/pricing/camperPricingLogic.js
- **Update JsonEditor to new package**
- **Fix lark pricing logic**
- **Make unassigned camper list scrollable**
=> Update JSON editor

client/src/components/Template/Template.tsx, client/src/hooks/api.ts, client/src/pages/EventAdminCampers/CamperEdit/AdminAttributesTab.tsx, client/src/pages/EventAdminRegistrations/EditTab/AdminAttributes.tsx, data/lark/lodgings.js
- **Order admin attributes by label**
- **Add cabins to lark camp**
- **Add registrationTypeLookup to report vars**
=> Report fixes

client/src/pages/EventAdminRegistrations/EditTab/AdminAttributes.tsx
=> Fix Registrations tab, Admin Attributes

client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingRequested.tsx, client/src/global.d.ts, client/src/hooks/api.ts, client/src/pages/EventAdminLodging/TreeView/LodgingEditForm.tsx, server/camphoric/lodging.py
- **Add ability to edit lodging capacity**
- **Allow capacity overrides for lodging**
=> Allow capacity overrides

data/harmony/camperSchema.js, data/harmony/confirmationEmailTemplate.js, data/harmony/confirmationPageTemplate.js, data/harmony/registrationSchema.js, data/harmony/registrationUISchema.js, data/loadAllData.js
- Readd events to import
- Fix deadline for early bird rate (harmony) fixes #535
- Change email conf (harmony) fixes #531
- Change campership desc (harmony) fixes #533
- Change conf page wording (harmony) fixes #530
- Fix reg form (harmony) fixes #529
- Add link for workshop thread (harmony) fixes #532
=> More harmony edits

client/Dockerfile, client/package-lock.json, client/package.json, client/src/components/PayPalProvider.tsx, client/src/pages/Register/PayPalButtons.tsx, client/src/pages/Register/PaymentStep.tsx, client/src/store/register/api.ts, client/src/store/register/registerFormSlice.ts, data/harmony/preSubmitTemplate.js, data/harmony/testRegistrations.js, docker-compose.yml, package.json, server/Dockerfile, server/camphoric/views.py, server/tests/test_views.py
- Fix test registrations (harmony)
- Update post-submit text (harmony) fixes #538
- Update docker files to not use alpine
- Update paypal scripts
=> More fixes for harmony

data/Dockerfile, data/harmony/confirmationEmailTemplate.js
=> Fix conf email template

.github/workflows/django.yml, .github/workflows/react.yml, Vagrantfile, ansible/group_vars/all.yml, ansible/roles/camphoric/defaults/main.yml, ansible/roles/camphoric/tasks/import_sample_data.yml, ansible/roles/camphoric/tasks/setup_django.yml, ansible/roles/camphoric/tasks/setup_react_development.yml, ansible/roles/camphoric/templates/camphoric.service.j2, ansible/roles/camphoric/templates/settings.py.j2, client/src/pages/EventAdminCampers/CamperEdit/FeesTab.tsx, server/camphoric_server/settings.py, vagrant-command-help
- **Improve VM setup**
- **Fix filtering for custom fees**
fixes #564
=> Fix filter on custom charges

ansible/roles/camphoric/tasks/import_sample_data.yml, data/ltacampout/confirmationEmailTemplate.js, data/ltacampout/dates.js, data/ltacampout/registrationSchema.js, vagrant-command-help
- **Add ansible option for not running `npm install`**
- **Add times to campout reg**
=> More campout fixes
