server/camphoric/pricing.py
server/tests/test_pricing.py
server/tests/test_views.py

This is to allow calculating intermediate variables in the pricing logic. We'll need this for calculating age in Familycamp and likely others.

Revise pricing logic structure

---

client/src/components/AdminPage/GuardedRoute.tsx
client/src/components/AdminPage/components/EventAdmin/EventAdmin.tsx
client/src/components/AdminPage/components/EventChooser.tsx
client/src/components/AdminPage/components/OrganizationChooser.tsx
client/src/components/AdminPage/hooks.ts
client/src/components/App/App.tsx

After talking with @evinism this evening, he mentioned that the context API is really meant for what I'm using hooks for, since the context api is used to persist global state, similar to redux.
This implements that.

Change api call hooks to context api hooks

---

server/camphoric/pricing.py

I did my best to fix this, hopefully this looks kosher...
I was getting this when trying to register with family week:
Request Method: | POST
-- | --
http://localhost:8000/api/events/1/register
3.1.3
TypeError
unsupported operand type(s) for +: 'NoneType' and 'int'
/Users/will/Sources/camphoric/server/camphoric/pricing.py, line 74, in calculate_price
/Users/will/.local/share/virtualenvs/server-BDZILzX2/bin/python
3.9.0
['/Users/will/Sources/camphoric/server',  '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',  '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9',  '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', …

Fix error in python logic

---

client/src/components/RegisterPage/RegisterPage.tsx
data/lark/loadData.mjs

The Form component from '@rjsf/bootstrap-4' broke our bootstrap-3 styling and customized DescriptionField that renders HTML, causing the Lark reg form to fail to render. This fixes that by reverting to Form from '@rjsf/core' for now for the RegistrationPage.
Also includes a fix for a bug in the lark loadData script.

 Revert to Form from '@rjsf/core' for RegisterPage 

---

server/Pipfile
server/Pipfile.lock
server/camphoric/urls.py
server/camphoric/views.py
server/camphoric_server/settings.py
server/setup.cfg
server/tests/test_views.py

We talked about doing authentication with HttpOnly session cookies as a more secure option than the token-based auth we currently have. We put the idea on hold because we couldn't find any off-the-shelf implementations for Django REST Framework. It turns out not to be not too complicated.
The main complication is dealing with CSRF tokens. The solution here is to do a `GET /api/set-csrf-cookie`, then include the value of the `csrftoken` cookie in the `X-CSRFToken` header in subsequent POST/PUT/PATCH/DELETE requests.

Implement cookie-based login

---

client/src/navigation/EventAdminContainer/NavBar.tsx
client/src/navigation/EventAdminContainer/index.tsx
client/src/navigation/RouterConfig.tsx
client/src/pages/EventAdmin/Home.tsx
client/src/pages/EventAdmin/Lodging.tsx
client/src/pages/EventAdmin/Registrations.tsx
client/src/pages/EventAdmin/Reports.tsx
client/src/pages/EventAdmin/Settings.tsx

Since the url params aren't available in subroutes (until react-router-dom v6, where routing and subrouting is rewritten), we have to pass the event in as a prop.

Fix navbar links

---

client/Dockerfile
doc/development.md
docker-compose.yml
remove-unused-docker-artifacts

While working on the rebuilding of the react container, I found it handy to delete just the react container, and cleanup after than, and then just rebuild react.  The splitting of these scripts made that possible
The way that Dockerfile and docker-compose.yml work together means that when the container is built the yarn.lock could change if you just use `yarn [install]`. The --frozen-lockfile prevents any updates when the container is first built. 
After the build, docker-compose will run the container, mounting its volumes, overwriting any changes made to the container during the build phase.
There is also one unused volume that wasn't doing anything.
```
./remove-all-docker-artifacts react
docker-compose up -d --no-deps --build react
```

Fix little docker problems

---

server/camphoric/serializers.py
server/camphoric/urls.py
server/camphoric/views.py
server/tests/test_views.py

Created user serializer, along with user view set and urls.
Returns user(s) without passwords. Currently, users created without a password are set an unusable password. We want to be able to then send that user a link to set their password. Admins are able to edit details of other admins except for password.
NEXT STEPS
create separate flow to handle passwords (endpoint for user to set password via email, endpoint for user to change password given current password)
LoginView and UserView to return serialized user object (call user serializer on user object) or return a 401 if no one is logged in
QUESTIONS
How does LogoutView need to change?

Create user views, user serializer,  and CRUD tests for user endpoints

---

client/src/global.d.ts
client/src/hooks/admin.ts
client/src/navigation/GuardedRoute.tsx
client/src/navigation/Login/index.tsx
server/camphoric/views.py
server/tests/test_views.py

Changed login to return serialized user objects. Testing works for
serialized user objects. Frontend login to also expects entire
user objects.

Implement user serializer

---

data/lark/loadData.mjs
data/lark/lodgings.mjs
data/lark/registrationUISchema.mjs
server/camphoric/lodging.py
server/camphoric/views.py
server/tests/test_get_lodging_schema.py
server/tests/test_views.py

Generate a schema for lodging options based on the lodging tree. Renders as a series of `<select>` menus, where each selection causes the next menu to appear.
We still need to implement disabling options where there is no remaining capacity (see @evinism's comment below)

Generate lodging schema for registration form

---

.github/workflows/django.yml
server/camphoric/views.py
server/camphoric_server/urls.py
server/frontend_bootstrap/urls.py
server/tests/test_views.py

The code for merging the lodging UI schema was overwriting the camper UI schema rather than merging the two.

Fix UI schema merge logic

---

docker-compose.yml
server/Pipfile
server/Pipfile.lock

We aren't ready to upgrade, and if we don't set this, every time we try to install with pipenv it will try and upgrade

Fix django version to <4

---

client/package-lock.json
client/package.json
client/src/components/JsonEditor/JsonEditor.tsx
client/src/components/JsonSchemaForm/fields/Address/index.tsx
client/src/components/JsonSchemaForm/index.tsx
client/src/components/JsonSchemaForm/templates/Object.tsx
client/src/components/JsonSchemaForm/widgets/Select.tsx
client/src/hooks/api.ts
client/src/navigation/EventAdminContainer/NavBar.tsx
client/src/navigation/EventAdminContainer/index.tsx
client/src/pages/EventAdmin/Lodging.tsx
client/src/pages/EventAdminCampers/EventAdminCampers.tsx
client/src/pages/EventAdminHome/EventAdminHome.tsx
client/src/pages/EventAdminRegistrations/EditTab/EditTab.tsx
client/src/pages/EventAdminRegistrations/EditTab/RegistrationSearchResult.tsx
client/src/pages/EventAdminRegistrations/SpecialRegTab/RegTypeModal.tsx
client/src/pages/EventAdminRegistrations/SpecialRegTab/SpecialRegTab.tsx
client/src/pages/EventAdminReports/EventAdminReports.tsx
client/src/pages/EventAdminReports/ReportView.tsx
client/src/pages/EventAdminSettings/EditRegistrationTypes.tsx
client/src/pages/EventAdminSettings/EditSchemaTab.tsx
client/src/pages/EventAdminSettings/EventAdminSettings.tsx
client/src/pages/EventChooser.tsx
client/src/pages/OrganizationChooser.tsx

This does the following:
- Move store/hooks->hooks/api
- Add duplicate import eslint rule
- Remove duplicate imports
- Update react-scripts
- Update modules via run `npm audit fix`

Move store/hooks->hooks/api and housekeeping

---

client/src/components/Default.tsx
data/loadAllData.mjs
docker-compose.yml
reset-db
server/camphoric/models.py
server/camphoric/urls.py
server/camphoric/views.py
server/tests/test_models.py
server/tests/test_views.py

This adds:
- A method to the Event model which checks if the event's registration is open
- A new api endpoint that lists the current events and if they're open
- Rework the root react view so that it lists the events and links to their
registration pages
It also adds these quick fixes:
- Fix health check for docker postgres
- Fix reset script

Add list of events feature

---

data/loadOrganizations.mjs

- log and exit on API error response to help with debugging
- use default values for email account env variables in case they are not set
This gets `loadAllData.mjs` working for me. I didn't figure why these two environment variables were not set despite being set in env/local/shared.env. @willfulbard, any thoughts?

Fall back to email account defaults in loadOrganizations

---

client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingRequested.tsx
client/src/components/JsonSchemaForm/fields/LodgingRequested/LodgingSelect.tsx
client/src/components/JsonSchemaForm/fields/LodgingRequested/index.ts
client/src/components/JsonSchemaForm/index.tsx
client/src/pages/Register/index.tsx
data/lark/camperMeals.js
data/lark/camperSchema.js
data/lark/testRegistrations.js
data/lark_campout/testRegistrations.js
server/camphoric/lodging.py
server/camphoric/views.py
server/tests/test_get_lodging_schema.py
server/tests/test_views.py

- Create custom lodging component
- This component allows us to control lodging selection on the front end, while keeping the schema simple
- Add custom local storage key per event
- I was seeing a little bit of data conflict between the lark campout data from an unsubmitted registration and the new lark camp event.  This should prevent conflicts, basically siloing the local storage to a specific event + start date
- Create better serialization of data
- "better" is probably not the right word, more like just getting it working.
- Fix tests
- Some of the tests were simplified, and might just need to be removed, since the backend logic is greatly simplified
TODO:
There's a lot of code cleanup to do in the lodging department.  Most of the tree stuff can probably be ripped out, but I would …

Create better lodging interface

---

client/src/components/PayPalProvider.tsx
client/src/pages/Register/PayPalButtons.tsx
client/src/pages/Register/PaymentStep.tsx

- Fix the issue that required React.memo to prevent re-rendering our PayPalButtons, because we need the component to re-render to reflect changes in the payment amount based on the deposit choice
- Work around weird behavior of PayPalButtons from @paypal/react-paypal-js where it ignores prop updates

Fix PayPal amount not reflecting deposit choice

---

client/src/components/Template/handlebarsHelpers.ts
client/src/global.d.ts
client/src/hooks/api.ts
docker-compose.yml

- Bump postgres version to 14
- Add fullPath string to lodging lookup
- Add some new helpers
Here is an example of how some of the new helpers could be used:
```
| Last Name | First Name | Age | Lodging | Chore |
| --------- | ---------- | --- | ------- | ----- |
{{#eachLookupSort campers 'lodging' 'lodgingLookup' 'fullPath'}}
| {{this.attributes.last_name}} | {{this.attributes.first_name}} | {{this.attributes.age}} | {{getLodgingValue lodging 'fullPath'}}  | {{this.attributes.chore}} |
{{/eachLookupSort}}
```
Result:

Add helpers for reports

---

client/src/components/Template/Template.tsx
client/src/components/Template/index.ts
client/src/components/TemplateHelp/HelperDocs.tsx
client/src/components/TemplateHelp/TemplateHelp.tsx
client/src/components/TemplateHelp/index.ts
client/src/components/TemplateHelp/styles.scss
client/src/pages/EventAdminReports/EventAdminReports.tsx
client/src/pages/EventAdminReports/ReportEditForm.tsx
client/src/pages/EventAdminReports/ReportTab.tsx

Adds the ability to download raw JSON data that is used in templates.  This will aid in us transitioning away from handlebars templates.
Eventually we'll probably use https://pypi.org/project/jinja-cli/

Add download button for json data

---

data/harmony/camperSchema.js
data/harmony/confirmationEmailTemplate.js
data/harmony/preSubmitTemplate.js
data/harmony/pricing/camperPricingLogic.js
data/harmony/registrationSchema.js
data/harmony/registrationUISchema.js
data/harmony/testRegistrations.js

- Fix #419 - harmony preSubmit template
- Fix #431 - Membership portion of reg form
- Fix #428 - make campership request optional
- Fix #432 - Add linens to camp harmony
- Fix #427 - Note required fields
- Fix #415 - Update harmony confirmation email

More Camp Harmony fixes

---

server/tests/test_mail.py

closes #466 
Based on the test failure message in #466, this should add enough wiggle room to make it fail less often.

Increase timing tolerance in mail test
